### ISSUE TITLE
Could you expand on how to send image updates / where to specify where to get new images?

### ISSUE THREAD

**Issue by ben68165** [codetiger/ePaper-display-using-ESP32#1]
Hi, this is exactly what I was looking for to display images on the eInk display. I got the firmware flashed to the esp32 and the wifi connected, but I am unable to figure out where i can specify the location the esp32 should get the new image, or how the new image should be send to it. Could you please elaborate? 
p.s.: i could not access the specified discord channel, that's why I'm trying it here. 
Thanks so much.
Ben

**Comment by codetiger** [comment]
Hi @ben68165,
You can use the send.py file (https://github.com/codetiger/ePaper-display-using-ESP32/blob/main/send.py) for sending the images through socket connection. In my case, I am using a RPi home server to send the images every few minutes.
