### ISSUE TITLE
[Question] Downloading & displaying an image

### ISSUE THREAD

**Issue by jantielens** [codetiger/ePaper-display-using-ESP32#2]
First of all: amazing work!

Your code is "push" model, where a server sends a picture to the ESP32. Would it be possible to change your code and have a "pull" model instead, where the ESP32 will download an image (over http, hosted on a web server) and displays it? I'm trying to build a photo frame that displays an image like every 5 minutes or something like that. 

Thanks for any suggestions you might have!

**Comment by codetiger** [comment]
There are lot of examples to download an image using wificlient in ESP32. But remember, ESP32 has very less RAM to decode JPEG or uncompress png formats. It's not impossible, however in this project I've made it easier for a server to handle the load and keep the photo frame as simple a possible,.

**Comment by jantielens** [comment]
Thanks for your reply! <3

Would hosting the image in an easy-to-consume format help? For example a BMP or just the raw bits for every pixel? 
Also, I have ESP32 with an SD card, do you see any (memory) limitations if I'd load a bitmap from the SD card and display it like that?

**Comment by codetiger** [comment]
If you have a sd card, then it’s easy to push the data directly. Based on what format the display supports, you can store in the same format so the mcu has to just put the data directly. 
in my case I had lot of scripts doing face recognition and pushing photos of a particular person so I used a push method
